In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from importlib import reload
import warnings
warnings.simplefilter("ignore")
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [24]:
coaster_df = pd.read_csv('data/prepped/roller_coasters.csv')
coaster_df.head()
coaster_df.status = coaster_df.status.str[7:].astype('category')

In [25]:
coaster_df.status.value_counts()

operating             2172
closed.definitely      439
announced               42
construction            41
unknown                 34
closed.temporarily      25
relocated               22
retracked               16
rumored                 11
Name: status, dtype: int64

In [28]:
coaster_df.head()

,name,material_type,seating_type,speed,height,length,num_inversions,manufacturer,park,status
0,Goudurix,Steel,Sit Down,75.0,37.0,950.0,7.0,Vekoma,Parc Asterix,operating
1,Dream catcher,Steel,Suspended,45.0,25.0,600.0,0.0,Vekoma,Bobbejaanland,operating
2,Alucinakis,Steel,Sit Down,30.0,8.0,250.0,0.0,Zamperla,Terra Mítica,operating
3,Anaconda,Wooden,Sit Down,85.0,35.0,1200.0,0.0,William J. Cobb,Walygator Parc,operating
4,Azteka,Steel,Sit Down,55.0,17.0,500.0,0.0,Soquet,Le Pal,operating

In [29]:
coaster_df[coaster_df.status == 'rumored']
coaster_df.iloc[2591,:] = pd.Series({'name':'Orion','material_type':'Steel','seating_type':'Sit Down','speed':91.0,'height':287.0,'length':5321.0,'num_inversions':0,'manufacturer':'B&M','park':'Kings Island','status':'operating'})
coaster_df.iloc[2592,:] = pd.Series({'name':'Ice Breaker','material_type':'Steel','seating_type':'Sit Down','speed':52.0,'height':93.0,'length':1900.0,'num_inversions':0,'manufacturer':'Premier Rides','park':'SeaWorld Orlando','status':'operating'})
coaster_df.iloc[2669,:] = pd.Series({'name':'Velocicoaster','material_type':'Steel','seating_type':'Sit Down','speed':70.0,'height':155.0,'length':4700.0,'num_inversions':4,'manufacturer':'Intamin','park':'Universal Studios Islands of Adventure','status':'operating'})
coaster_df.iloc[2668,:] = pd.Series({'name':'Texas Stingray','material_type':'Hybrid','seating_type':'Sit Down','speed':55.0,'height':100.0,'length':3379.0,'num_inversions':0,'manufacturer':'GCI','park':'SeaWorld San Antonio','status':'operating'})
coaster_df.iloc[2601,:] = pd.Series({'name':'Namazu','material_type':'Steel','seating_type':'Sit Down','speed':42.9,'height':52.5,'length':1916.0,'num_inversions':0,'manufacturer':'Intamin','park':'Vulcania','status':'operating'})

In [53]:
coaster_df = coaster_df[coaster_df.status != 'rumored']
coaster_df[coaster_df.material_type == 'na']
coaster_df.loc[coaster_df.name == 'Escape from Madagascar', 'material_type'] = 'Steel'
coaster_df = coaster_df[coaster_df.material_type != 'na']
coaster_df.dropna()

,name,material_type,seating_type,speed,height,length,num_inversions,manufacturer,park,status
0,Goudurix,Steel,Sit Down,75.0,37.0,950.0,7.0,Vekoma,Parc Asterix,operating
1,Dream catcher,Steel,Suspended,45.0,25.0,600.0,0.0,Vekoma,Bobbejaanland,operating
2,Alucinakis,Steel,Sit Down,30.0,8.0,250.0,0.0,Zamperla,Terra Mítica,operating
3,Anaconda,Wooden,Sit Down,85.0,35.0,1200.0,0.0,William J. Cobb,Walygator Parc,operating
4,Azteka,Steel,Sit Down,55.0,17.0,500.0,0.0,Soquet,Le Pal,operating
...,...,...,...,...,...,...,...,...,...,...
2751,Wild Lightnin',Steel,Sit Down,40.0,15.0,359.0,0.0,L&T Systems,Lake Winnie,operating
2753,Cannon Ball,Wooden,Sit Down,80.0,21.0,692.0,0.0,Philadelphia Toboggan Coaster,Lake Winnie,operating
2754,Hell Cat,Wooden,Sit Down,90.0,33.0,793.0,0.0,S&S,Clementon Park,operating
2765,African Spin,Steel,Sit Down,30.0,7.0,113.0,0.0,SBF,Tatzmania Löffingen,operating
2799,Unnamed Atlantica Supersplash Clone,Steel,Sit Down,80.0,30.0,390.0,0.0,Mack,Le Pal,announced

In [59]:
coaster_df.loc[coaster_df.manufacturer == 'na','manufacturer'] = ''
coaster_df = coaster_df.dropna()
coaster_df.shape

(1206, 10)